ETuple: Avoid race conditions wrt. defining a tuple class.
Symptom was:
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at erjang.ERT.defineClass(ERT.java)
	...
Caused by: java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "erjang/ETuple40"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:788)
	...